### ISSUE TITLE
cargo crev query should emit document separators

### ISSUE THREAD

**Issue by Nemo157** [crev-dev/cargo-crev#240]
Trying to pipe `cargo crev query review` through something like `yaml2json | jq` to analyze the reviews is difficult as it only sees a single yaml document and will just end up overwriting all the properties and only getting the last review, with potentially some unset keys from earlier reviews.

Emitting each record as an [explicit document](https://yaml.org/spec/1.2/spec.html#id2801301) by prefixing with a [directives end marker](https://yaml.org/spec/1.2/spec.html#marker/directives%20end/) will allows tools to detect each separate record and process them independently.

For example, the first two reviews I get would be rendered as:

```yaml
---
version: -1
date: "2019-07-23T23:56:46.264374800-07:00"
from:
  id-type: crev
  id: 6OZqHXqyUAF57grEY7IVMjRljdd9dgDxiNtr1NF1BdY
  url: "https://github.com/MaulingMonkey/crev-proofs"
package:
  source: "https://crates.io"
  name: actix-codec
  version: 0.1.2
  revision: 16856c7d3fa725c65ccec5940ab8331ad3c270fc
  digest: 8PFMDiHDzb8WvsRiZLdlDSa7tgD3TzUcjUalTbId34I
review:
  thoroughness: none
  understanding: none
  rating: negative
comment: |
  https://64.github.io/actix/  https://github.com/actix/actix-web/pull/968#issuecomment-509894555
---
version: -1
date: "2019-07-23T23:57:54.748844900-07:00"
from:
  id-type: crev
  id: 6OZqHXqyUAF57grEY7IVMjRljdd9dgDxiNtr1NF1BdY
  url: "https://github.com/MaulingMonkey/crev-proofs"
package:
  source: "https://crates.io"
  name: actix-connect
  version: 0.2.1
  revision: 411e31786f72d69a349204f04578929d9a5214c3
  digest: RQsaFHsELtqrGMTx0U5xy_ErJUzEghIT9AM2FKRvzjc
review:
  thoroughness: none
  understanding: none
  rating: negative
comment: |
  https://64.github.io/actix/  https://github.com/actix/actix-web/pull/968#issuecomment-509894555
```
