### ISSUE TITLE
Add `alternatives: ` field

### ISSUE THREAD

**Issue by dpc** [crev-dev/cargo-crev#260]
So users can propose alternative crates to use.
Many times I'm looking for a crate to use, and I could use some recommendations.

**Comment by dpc** [comment]
```
----- BEGIN CREV PROOF -----
kind: package review
version: -1
date: "2019-10-27T23:06:11.495678988-07:00"
from:
  id-type: crev
  id: FYlr8YoYGVvDwHQxqEIs89reKKDy-oWisoO0qXXEfHE
  url: "https://github.com/dpc/crev-proofs"
package:
  source: "https://crates.io"
  name: term
  version: 0.6.1
  revision: 61d944cfb767a00313497997878f9f2a35252b5c
  digest: O1k-e-mqKDyrJIaEr3v1JO7Rb38RKCoXCsNUCplArw4
flags:
  unmaintained: true
alternatives:
  - source: "https://crates.io"
    name: crossterm
  - source: "https://crates.io"
    name: termcolor
  - source: "https://crates.io"
    name: yansi
----- SIGN CREV PROOF -----
mHcbkkhqM2hjrGRbEtUqpqBTADVgeIXeFj_fCUT-vTtViISCpnDN0wbHrkWk7Nxkz7gw0czgiCO5j-CA7U_EDA
----- END CREV PROOF -----
```
