### ISSUE TITLE
New proof serialization format

### ISSUE THREAD

**Issue by dpc** [crev-dev/cargo-crev#262]
As a followup to #252 i've pushed to `master` an initial version of a new proof format (backward compatibility code included).

Example:

```
----- BEGIN CREV PROOF -----
kind: package review
version: -1
date: "2019-10-26T23:40:18.348667543-07:00"
from:
  id-type: crev
  id: FYlr8YoYGVvDwHQxqEIs89reKKDy-oWisoO0qXXEfHE
  url: "https://github.com/dpc/crev-proofs"
package:
  source: "https://crates.io"
  name: nodrop
  version: 0.1.13
  revision: 08c20edbb0c62939904759b9c14095ca0fd07d03
  digest: Kh2VjXR5hV5D074ujzyFV-R9s4rsHfVl7kfd2R2BT38
comment: "Some `unsafe`, but LGTM\n"
----- SIGN CREV PROOF -----
sAvdgZhwX-ZtUcWwgZ8qUQG0wF8ddswzRI-hJIdLtAx8LPyjbrVbleHOh1HwmxckcvpcscCvOPLcmO6g73VEAg
----- END CREV PROOF -----
```

The differences are rather minor: 

* the type of the proof is now named `kind`, like in kubernets yamls; I think it sounds as good and is less packed with meaning in programming languages world
* the `kind` (type) is now a field instead of being part of the separators. that makes it easier to parse, easier to handle proof types defined by other software; it also makes that information signed over
* I've added spaces in between `------` . I just think it is more readable, and doesn't hurt anything

Users of `master` will now produce proofs that only other users of `master` (and future versions) would understand. Format is still a subject for discussion and changes. Code is initial, and very lightly tested.

**Feedback is very appreciated**

**Comment by dpc** [comment]
@ffranr I believe you should be fully unblocked with defining your own kind of proofs

**Comment by ffranr** [comment]
@dpc That's a lot of work. Good effort! Your changes look good from that I can tell so far. I'll have a go at defining my own proof.

**Comment by ffranr** [comment]
@dpc Don't you need a `PROOF_HEADER_PREFIX_ALT` variant here also? `PROOF_HEADER_PREFIX` lack a space after `-----`.

https://github.com/crev-dev/cargo-crev/blob/5655b127eed37438a3089b84ba16cac72195b40a/crev-data/src/proof/mod.rs#L93

**Comment by dpc** [comment]
I am not sure what do you mean @ffranr . https://github.com/crev-dev/cargo-crev/blob/0865e4d291f41c444788070f059405ebb045f5b0/crev-data/src/proof/mod.rs#L111 In the legacy format there were no spaces between `-----` and words. With an exception of trust proof which had a weird space in the suffix. https://github.com/dpc/crev-proofs/blob/3ea7e440f1ed84f5a333741e71a90e2067fe9cfc/FYlr8YoYGVvDwHQxqEIs89reKKDy-oWisoO0qXXEfHE/trust/2019-10-GkN7aw.proof.crev#L1

**Comment by dpc** [comment]
```
----- BEGIN CREV PROOF -----
kind: package review
version: -1
date: "2019-10-27T23:06:11.495678988-07:00"
from:
  id-type: crev
  id: FYlr8YoYGVvDwHQxqEIs89reKKDy-oWisoO0qXXEfHE
  url: "https://github.com/dpc/crev-proofs"
package:
  source: "https://crates.io"
  name: term
  version: 0.6.1
  revision: 61d944cfb767a00313497997878f9f2a35252b5c
  digest: O1k-e-mqKDyrJIaEr3v1JO7Rb38RKCoXCsNUCplArw4
flags:
  unmaintained: true
alternatives:
  - source: "https://crates.io"
    name: crossterm
  - source: "https://crates.io"
    name: termcolor
  - source: "https://crates.io"
    name: yansi
----- SIGN CREV PROOF -----
mHcbkkhqM2hjrGRbEtUqpqBTADVgeIXeFj_fCUT-vTtViISCpnDN0wbHrkWk7Nxkz7gw0czgiCO5j-CA7U_EDA
----- END CREV PROOF -----
```

Implementing #260
