### ISSUE TITLE
How to close/solve a "crev review issue"?

### ISSUE THREAD

**Issue by LucianoBestia** [crev-dev/cargo-crev#332]
In my crate I `cargo crev verify` and get one line with issues :
```
status issues flgs crate                version         latest_t 
pass    1   1 CB__ num-traits           0.2.11          =
```
The status is `pass`, but there is one red and one yellow issue.
What exactly this represents?
`cargo crev repo query issue num-traits` returns:
```
date: "2019-08-30T..."
from:
    url: "https://github.com/HeroicKatora/crev-proofs"
version: 0.2.6
rating: positive
issues:
  - id: "https://github.com/rust-num/num-traits/issues/125"
  severity: medium
```
I went to the issue on Github to check and that issue is solved/closed after 0.2.6.
Now we have version 0.2.11, but this same issue is still visible.
How to solve/close this issue to not show in crev for newer versions of the crate?
